openapi: 3.0.3

info:
  title: Duke Encounters API
  description: |
    **Duke Encounters** is a demo web application with a Spring Boot backend. It is using OpenAPI to generate all endpoints and models and requires a Keycloak.
  version: v1
  contact:
    name: Dominik Schadow
    email: dominikschadow@gmail.com
    url: https://github.com/dschadow/KeycloakSecurity
  license:
    url: https://github.com/dschadow/KeycloakSecurity/blob/main/LICENSE
    name: Apache License 2.0

servers:
  - url: 'http://localhost:8080'

tags:
  - name: Encounter
    description: Mostly authorized endpoints to modify and retrieve encounters with all details
  - name: Confirmation
    description: Authorized endpoints to modify and retrieve confirmations for existing encounters

paths:
  /v1/encounters:
    get:
      summary: Get a paginated list with all Duke encounters
      description: Authorized endpoint returning a paginated list of all Duke encounters with all details
      tags:
        - Encounter
      operationId: readEncounters
      responses:
        200:
          description: A list of Duke encounters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncounterList'
    post:
      summary: Create a new encounters entry
      description: Authorized endpoint creating a new encounters entry
      tags:
        - Encounter
      operationId: createEncounter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEncounter'
      responses:
        201:
          description: Successfully created a new encounter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encounter'
  /v1/encounters/latest:
    get:
      summary: Get a list with the latest Duke encounters
      description: Public endpoint returning a list of the latest Duke encounters
      tags:
        - Encounter
      operationId: readLatestEncounters
      security: []
      responses:
        200:
          description: A list of the latest Duke encounters
          content:
            application/json:
              examples:
                multiple:
                  summary: Three encounters on two events
                  value:
                    items:
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
                        event: JavaOne
                        event_date: 2022-10-16
                        location: Las Vegas
                        creation_date: 2022-10-17
                        description: At the bar
                        likeliness: 10
                        confirmations: 27
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa5
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
                        event: JavaOne
                        event_date: 2022-10-16
                        location: Las Vegas
                        creation_date: 2022-10-18
                        description: In the pool
                        likeliness: 5
                        confirmations: 3
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa7
                        event: JavaLand
                        event_date: 2021-03-21
                        location: Phantasialand
                        creation_date: 2021-03-30
                        description: On the roller coaster
                        likeliness: 1
                        confirmations: 0
                single:
                  summary: One encounter on a single event
                  value:
                    id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                    user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa7
                    event: JavaLand
                    event_date: 2021-03-21
                    location: Phantasialand
                    creation_date: 2021-03-30
                    description: On the roller coaster
                    likeliness: 1
                    confirmations: 0
                none:
                  summary: No encounters
                  value:
                    items: []
              schema:
                $ref: '#/components/schemas/EncounterList'
  /v1/encounters/{id}:
    get:
      summary: Get a single encounter
      description: Authorized endpoint returning a single encounter with all details
      tags:
        - Encounter
      operationId: readEncounter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The encounter's ID
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      responses:
        200:
          description: A single encounter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encounter'
        404:
          description: Encounter not found
  /v1/encounters/{id}/confirmations:
    post:
      summary: Create a new confirmation for an encounter
      description: Authorized endpoint creating a new confirmation for an existing encounter
      tags:
        - Encounter
      operationId: createConfirmation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The encounter's ID
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConfirmation'
      responses:
        201:
          description: Successfully confirmed an encounter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encounter'
  /v1/confirmations/latest:
    get:
      summary: Get a list with the latest encounter confirmations
      description: Authorized endpoint returning a list of the latest encounter confirmations
      tags:
        - Confirmation
      operationId: readLatestConfirmations
      security: []
      responses:
        200:
          description: A list of the latest confirmations
          content:
            application/json:
              examples:
                multiple:
                  summary: Three confirmations on two encounters
                  value:
                    items:
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
                        event: JavaOne
                        event_date: 2022-10-16
                        location: Las Vegas
                        creation_date: 2022-10-17
                        encounter_date: 2022-10-17
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa5
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
                        event: JavaOne
                        event_date: 2022-10-16
                        location: Las Vegas
                        creation_date: 2022-10-18
                        encounter_date: 2022-10-18
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa7
                        event: JavaLand
                        event_date: 2021-03-21
                        location: Phantasialand
                        creation_date: 2021-03-30
                        encounter_date: 2021-03-30
                single:
                  summary: One confirmation on a single event
                  value:
                    id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                    user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa7
                    event: JavaLand
                    event_date: 2021-03-21
                    location: Phantasialand
                    creation_date: 2021-03-30
                    encounter_date: 2021-03-30
                none:
                  summary: No confirmations
                  value:
                    items: []
              schema:
                $ref: '#/components/schemas/ConfirmationList'
  /v1/confirmations/own:
    get:
      summary: Get a list with all encounter confirmations belonging to the current user
      description: Authorized endpoint returning a list of all encounter confirmations of the current user
      tags:
        - Confirmation
      operationId: readOwnConfirmations
      security: []
      responses:
        200:
          description: A list of own confirmations
          content:
            application/json:
              examples:
                multiple:
                  summary: Two confirmations on two encounters
                  value:
                    items:
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
                        event: JavaOne
                        event_date: 2022-10-16
                        location: Las Vegas
                        creation_date: 2022-10-17
                        encounter_date: 2022-10-17
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
                        event: JavaLand
                        event_date: 2021-03-21
                        location: Phantasialand
                        creation_date: 2021-03-30
                        encounter_date: 2021-03-30
                single:
                  summary: One confirmation on a single event
                  value:
                    id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                    user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
                    event: JavaLand
                    event_date: 2021-03-21
                    location: Phantasialand
                    creation_date: 2021-03-30
                    encounter_date: 2021-03-30
                none:
                  summary: No confirmations
                  value:
                    items: []
              schema:
                $ref: '#/components/schemas/ConfirmationList'

components:
  schemas:
    EncounterList:
      type: object
      description: A list of Duke encounters
      properties:
        encounters:
          type: array
          items:
            $ref: '#/components/schemas/Encounter'
    Encounter:
      type: object
      description: Represents a Duke encounter with all available details
      example:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
        event: JavaOne
        event_date: 2022
        location: Las Vegas
        creation_date: 2022-10-17
        encounter_date: 2022-10-17
        description: At the bar
        likeliness: 10
        confirmations: 27
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        event:
          type: string
          minLength: 5
          maxLength: 50
        event_date:
          type: string
        encounter_date:
          type: string
          format: date
        location:
          type: string
          maxLength: 50
        creation_date:
          type: string
          format: date
        description:
          type: string
          maxLength: 1024
          nullable: true
        likeliness:
          type: integer
          minimum: 1
          maximum: 10
        confirmations:
          type: integer
          minimum: 0
          nullable: true
    CreateEncounter:
      type: object
      description: Create a new Duke encounter with all required information
      example:
        event: JavaOne
        description: At the bar
      properties:
        event:
          type: string
          minLength: 5
          maxLength: 50
        event_date:
          type: string
          format: date
        encounter_date:
          type: string
          format: date
        location:
          type: string
          maxLength: 50
        description:
          type: string
          maxLength: 1024
          nullable: true
    ConfirmationList:
      type: object
      description: A list of confirmations
      properties:
        encounters:
          type: array
          items:
            $ref: '#/components/schemas/Confirmation'
    Confirmation:
      type: object
      description: Represents a Duke encounter confirmation
      example:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
        event: JavaOne
        event_date: 2022
        location: Las Vegas
        creation_date: 2022-10-17
        encounter_date: 2022-10-17
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        event:
          type: string
          minLength: 5
          maxLength: 50
        event_date:
          type: string
        encounter_date:
          type: string
          format: date
        location:
          type: string
          maxLength: 50
        creation_date:
          type: string
          format: date
    CreateConfirmation:
      type: object
      description: Create a new confirmation of an existing encounter with all required information
      properties:
        encounter_id:
          type: string
          format: uuid
    User:
      type: object
      description: Represents a user of the web application
      example:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        username: The Duke
        creation_date: 21.09.2022
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
          minLength: 3
          maxLength: 20
        creation_date:
          type: string
          format: date
  securitySchemes:
    KeycloakToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8090/oauth2/authorize
          tokenUrl: http://localhost:8090/oauth2/authorize
          scopes: {}

security:
  - KeycloakToken: [ ]